--
-- PostgreSQL database dump
--


-- Dumped from database version 16.11 (Homebrew)
-- Dumped by pg_dump version 18.0

-- Started on 2026-01-16 13:23:31 MSK

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 216 (class 1259 OID 16391)
-- Name: courses; Type: TABLE; Schema: public; Owner: antonuzegov
--

CREATE TABLE public.courses (
    id bigint NOT NULL,
    badge character varying(255),
    difficulty character varying(255),
    duration_weeks integer,
    lessons_count integer,
    short_description character varying(2000),
    slug character varying(255) NOT NULL,
    tags character varying(500),
    title character varying(255) NOT NULL
);


ALTER TABLE public.courses OWNER TO antonuzegov;

--
-- TOC entry 215 (class 1259 OID 16390)
-- Name: courses_id_seq; Type: SEQUENCE; Schema: public; Owner: antonuzegov
--

ALTER TABLE public.courses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.courses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 16399)
-- Name: lessons; Type: TABLE; Schema: public; Owner: antonuzegov
--

CREATE TABLE public.lessons (
    id bigint NOT NULL,
    content text,
    "position" integer,
    title character varying(255) NOT NULL,
    course_id bigint NOT NULL
);


ALTER TABLE public.lessons OWNER TO antonuzegov;

--
-- TOC entry 217 (class 1259 OID 16398)
-- Name: lessons_id_seq; Type: SEQUENCE; Schema: public; Owner: antonuzegov
--

ALTER TABLE public.lessons ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.lessons_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3829 (class 0 OID 16391)
-- Dependencies: 216
-- Data for Name: courses; Type: TABLE DATA; Schema: public; Owner: antonuzegov
--

COPY public.courses (id, badge, difficulty, duration_weeks, lessons_count, short_description, slug, tags, title) FROM stdin;
1	Base	Лёгкая	8	20	Синтаксис, ООП, коллекции, исключения. Идеальный старт для новичков.	java-beginners	Синтаксис,Переменные,Условия,Циклы,Методы,ООП,Коллекции,Исключения	Java для начинающих
\.


--
-- TOC entry 3831 (class 0 OID 16399)
-- Dependencies: 218
-- Data for Name: lessons; Type: TABLE DATA; Schema: public; Owner: antonuzegov
--

COPY public.lessons (id, content, "position", title, course_id) FROM stdin;
1	Цель: поставить JDK, запустить Hello World.\n\nПример:\npublic class Main { ... }	1	Среда разработки и первый запуск	1
2	int, double, boolean, char, String. Ввод через Scanner.	2	Переменные и типы данных	1
3	Арифметика, сравнение, логика.	3	Операторы и выражения	1
4	nextInt/nextLine и частые ошибки.	4	Ввод данных (Scanner)	1
5	Ветвления и условия.	5	if / else	1
6	Меню и выбор действий.	6	switch	1
7	Повторы до условия.	7	while	1
8	Счётчик и итерации.	8	for	1
9	int[] и базовые операции.	9	Массивы	1
10	Параметры, return, перегрузка.	10	Методы	1
11	equals, contains, split, форматирование.	11	Строки (String)	1
12	Поля, методы, конструкторы.	12	ООП: классы и объекты	1
13	private, getters/setters.	13	Инкапсуляция	1
14	extends, super.	14	Наследование	1
15	переопределение, интерфейсы (intro).	15	Полиморфизм	1
16	try/catch/finally, свои исключения.	16	Исключения	1
17	ArrayList, базовые методы.	17	Коллекции: List	1
18	HashMap, ключ-значение.	18	Коллекции: Map	1
19	чтение/запись (intro).	19	Файлы (основы)	1
20	Консольный проект на закрепление.	20	Мини-проект	1
\.


--
-- TOC entry 3837 (class 0 OID 0)
-- Dependencies: 215
-- Name: courses_id_seq; Type: SEQUENCE SET; Schema: public; Owner: antonuzegov
--

SELECT pg_catalog.setval('public.courses_id_seq', 5, true);


--
-- TOC entry 3838 (class 0 OID 0)
-- Dependencies: 217
-- Name: lessons_id_seq; Type: SEQUENCE SET; Schema: public; Owner: antonuzegov
--

SELECT pg_catalog.setval('public.lessons_id_seq', 25, true);


--
-- TOC entry 3679 (class 2606 OID 16397)
-- Name: courses courses_pkey; Type: CONSTRAINT; Schema: public; Owner: antonuzegov
--

ALTER TABLE ONLY public.courses
    ADD CONSTRAINT courses_pkey PRIMARY KEY (id);


--
-- TOC entry 3683 (class 2606 OID 16405)
-- Name: lessons lessons_pkey; Type: CONSTRAINT; Schema: public; Owner: antonuzegov
--

ALTER TABLE ONLY public.lessons
    ADD CONSTRAINT lessons_pkey PRIMARY KEY (id);


--
-- TOC entry 3681 (class 2606 OID 16407)
-- Name: courses ukrbsoo34muf0lcryn4q2i0h3vc; Type: CONSTRAINT; Schema: public; Owner: antonuzegov
--

ALTER TABLE ONLY public.courses
    ADD CONSTRAINT ukrbsoo34muf0lcryn4q2i0h3vc UNIQUE (slug);


--
-- TOC entry 3684 (class 2606 OID 16408)
-- Name: lessons fk17ucc7gjfjddsyi0gvstkqeat; Type: FK CONSTRAINT; Schema: public; Owner: antonuzegov
--

ALTER TABLE ONLY public.lessons
    ADD CONSTRAINT fk17ucc7gjfjddsyi0gvstkqeat FOREIGN KEY (course_id) REFERENCES public.courses(id);


-- Completed on 2026-01-16 13:23:32 MSK

--
-- PostgreSQL database dump complete
--


